# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sl.ui'
#
# Created: Fri Jul 31 13:30:53 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.query_nb_frame = QtWidgets.QFrame(self.centralwidget)
        self.query_nb_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.query_nb_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.query_nb_frame.setObjectName("query_nb_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.query_nb_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.left_thr_label = QtWidgets.QLabel(self.query_nb_frame)
        self.left_thr_label.setObjectName("left_thr_label")
        self.gridLayout_3.addWidget(self.left_thr_label, 4, 0, 1, 1)
        self.right_thr_label = QtWidgets.QLabel(self.query_nb_frame)
        self.right_thr_label.setObjectName("right_thr_label")
        self.gridLayout_3.addWidget(self.right_thr_label, 5, 0, 1, 1)
        self.right_nb_size = QtWidgets.QSpinBox(self.query_nb_frame)
        self.right_nb_size.setEnabled(False)
        self.right_nb_size.setMaximum(1000000000)
        self.right_nb_size.setObjectName("right_nb_size")
        self.gridLayout_3.addWidget(self.right_nb_size, 3, 1, 1, 1)
        self.nb_checkbox = QtWidgets.QCheckBox(self.query_nb_frame)
        self.nb_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nb_checkbox.setChecked(False)
        self.nb_checkbox.setTristate(False)
        self.nb_checkbox.setObjectName("nb_checkbox")
        self.gridLayout_3.addWidget(self.nb_checkbox, 1, 0, 1, 1)
        self.left_nb_size = QtWidgets.QSpinBox(self.query_nb_frame)
        self.left_nb_size.setEnabled(False)
        self.left_nb_size.setMaximum(1000000000)
        self.left_nb_size.setObjectName("left_nb_size")
        self.gridLayout_3.addWidget(self.left_nb_size, 2, 1, 1, 1)
        self.right_size_label = QtWidgets.QLabel(self.query_nb_frame)
        self.right_size_label.setObjectName("right_size_label")
        self.gridLayout_3.addWidget(self.right_size_label, 3, 0, 1, 1)
        self.left_size_label = QtWidgets.QLabel(self.query_nb_frame)
        self.left_size_label.setObjectName("left_size_label")
        self.gridLayout_3.addWidget(self.left_size_label, 2, 0, 1, 1)
        self.right_nb_thr = QtWidgets.QSpinBox(self.query_nb_frame)
        self.right_nb_thr.setEnabled(False)
        self.right_nb_thr.setMaximum(1000000000)
        self.right_nb_thr.setObjectName("right_nb_thr")
        self.gridLayout_3.addWidget(self.right_nb_thr, 5, 1, 1, 1)
        self.left_nb_thr = QtWidgets.QSpinBox(self.query_nb_frame)
        self.left_nb_thr.setEnabled(False)
        self.left_nb_thr.setMaximum(1000000000)
        self.left_nb_thr.setObjectName("left_nb_thr")
        self.gridLayout_3.addWidget(self.left_nb_thr, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.query_nb_frame, 0, 1, 1, 1)
        self.buttons_frame = QtWidgets.QFrame(self.centralwidget)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_button = QtWidgets.QPushButton(self.buttons_frame)
        self.start_button.setObjectName("start_button")
        self.verticalLayout.addWidget(self.start_button)
        self.cancel_button = QtWidgets.QPushButton(self.buttons_frame)
        self.cancel_button.setEnabled(False)
        self.cancel_button.setObjectName("cancel_button")
        self.verticalLayout.addWidget(self.cancel_button)
        self.gridLayout.addWidget(self.buttons_frame, 1, 1, 1, 1)
        self.query_frame = QtWidgets.QFrame(self.centralwidget)
        self.query_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.query_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.query_frame.setObjectName("query_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.query_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.query_label = QtWidgets.QLabel(self.query_frame)
        self.query_label.setObjectName("query_label")
        self.gridLayout_2.addWidget(self.query_label, 0, 0, 1, 1)
        self.avg_label = QtWidgets.QLabel(self.query_frame)
        self.avg_label.setObjectName("avg_label")
        self.gridLayout_2.addWidget(self.avg_label, 3, 0, 1, 1)
        self.signal_label = QtWidgets.QLabel(self.query_frame)
        self.signal_label.setObjectName("signal_label")
        self.gridLayout_2.addWidget(self.signal_label, 1, 0, 1, 1)
        self.length_label = QtWidgets.QLabel(self.query_frame)
        self.length_label.setObjectName("length_label")
        self.gridLayout_2.addWidget(self.length_label, 2, 0, 1, 1)
        self.min_size = QtWidgets.QSpinBox(self.query_frame)
        self.min_size.setMaximum(1000000000)
        self.min_size.setObjectName("min_size")
        self.gridLayout_2.addWidget(self.min_size, 2, 2, 1, 1)
        self.signal_type = QtWidgets.QComboBox(self.query_frame)
        self.signal_type.setObjectName("signal_type")
        self.gridLayout_2.addWidget(self.signal_type, 1, 2, 1, 1)
        self.min_avg = QtWidgets.QSpinBox(self.query_frame)
        self.min_avg.setMaximum(1000000000)
        self.min_avg.setObjectName("min_avg")
        self.gridLayout_2.addWidget(self.min_avg, 3, 2, 1, 1)
        self.query_type = QtWidgets.QComboBox(self.query_frame)
        self.query_type.setObjectName("query_type")
        self.gridLayout_2.addWidget(self.query_type, 0, 2, 1, 1)
        self.max_size = QtWidgets.QSpinBox(self.query_frame)
        self.max_size.setMaximum(1000000000)
        self.max_size.setObjectName("max_size")
        self.gridLayout_2.addWidget(self.max_size, 2, 3, 1, 1)
        self.max_avg = QtWidgets.QSpinBox(self.query_frame)
        self.max_avg.setMaximum(1000000000)
        self.max_avg.setObjectName("max_avg")
        self.gridLayout_2.addWidget(self.max_avg, 3, 3, 1, 1)
        self.gridLayout.addWidget(self.query_frame, 0, 0, 1, 1)
        self.area_params_frame = QtWidgets.QFrame(self.centralwidget)
        self.area_params_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.area_params_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.area_params_frame.setObjectName("area_params_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.area_params_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.interval_label = QtWidgets.QLabel(self.area_params_frame)
        self.interval_label.setObjectName("interval_label")
        self.gridLayout_4.addWidget(self.interval_label, 0, 1, 1, 1)
        self.resolution_label = QtWidgets.QLabel(self.area_params_frame)
        self.resolution_label.setObjectName("resolution_label")
        self.gridLayout_4.addWidget(self.resolution_label, 1, 1, 1, 1)
        self.search_resolution = QtWidgets.QSpinBox(self.area_params_frame)
        self.search_resolution.setMinimum(1)
        self.search_resolution.setMaximum(1000000)
        self.search_resolution.setObjectName("search_resolution")
        self.gridLayout_4.addWidget(self.search_resolution, 1, 2, 1, 1)
        self.ms_label = QtWidgets.QLabel(self.area_params_frame)
        self.ms_label.setObjectName("ms_label")
        self.gridLayout_4.addWidget(self.ms_label, 1, 3, 1, 1)
        self.left_search_bound = QtWidgets.QLineEdit(self.area_params_frame)
        self.left_search_bound.setObjectName("left_search_bound")
        self.gridLayout_4.addWidget(self.left_search_bound, 0, 2, 1, 1)
        self.right_search_bound = QtWidgets.QLineEdit(self.area_params_frame)
        self.right_search_bound.setObjectName("right_search_bound")
        self.gridLayout_4.addWidget(self.right_search_bound, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.area_params_frame, 1, 0, 1, 1)
        self.mpl_waveform = MplWidget(self.centralwidget)
        self.mpl_waveform.setObjectName("mpl_waveform")
        self.gridLayout.addWidget(self.mpl_waveform, 2, 0, 1, 3)
        self.results_list = QtWidgets.QListWidget(self.centralwidget)
        self.results_list.setObjectName("results_list")
        self.gridLayout.addWidget(self.results_list, 0, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Searchlight"))
        self.left_thr_label.setText(_translate("MainWindow", "Left max threshold:"))
        self.right_thr_label.setText(_translate("MainWindow", "Right max threshold:"))
        self.nb_checkbox.setText(_translate("MainWindow", "Neighborhood"))
        self.right_size_label.setText(_translate("MainWindow", "Right size:"))
        self.left_size_label.setText(_translate("MainWindow", "Left size:"))
        self.start_button.setText(_translate("MainWindow", "Start Query"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel Query"))
        self.query_label.setText(_translate("MainWindow", "Query:"))
        self.avg_label.setText(_translate("MainWindow", "Average:"))
        self.signal_label.setText(_translate("MainWindow", "Signal:"))
        self.length_label.setText(_translate("MainWindow", "Length:"))
        self.query_type.setStatusTip(_translate("MainWindow", "Select query type"))
        self.query_type.setWhatsThis(_translate("MainWindow", "Query type"))
        self.interval_label.setText(_translate("MainWindow", "Search Interval:"))
        self.resolution_label.setText(_translate("MainWindow", "Search Resolution:"))
        self.ms_label.setText(_translate("MainWindow", "ms"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open SL JSON query file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

from mplwidget import MplWidget
